var fname = "Mahesh";
var mname = "Rameshrao";
var lname = "Sabnis";
console.log('Traditional Caoncatination ' + fname + '  ' + mname + '  ' + lname);
console.log('ES 6 String concatinatio using template string');
var fullName = fname + " " + mname + " " + lname;
console.log(fullName);
console.log(fullName.toUpperCase());
console.log(fullName.toLowerCase());
console.log(fullName.length);
